- README.md
While the test suite is available within the skeleton, there is no examples or documentation on how to actually structure the test specifications. This PR updates the documentation and showcases and example test specification.
> Better documentation around the test suite.

- package.json
> Updated repo path

- README.md
Adding a new section of the README regarding cloning.
> Readme: Cloning

- package.json
- run/tasks/build/gulp.js
> HTML assets now moved to dist folder.

- README.md
> updating readme with some docker details

- package.json
- run/index.js
- run/tasks/scripts/gulp.js
- run/tasks/styles/gulp.js
- run/tasks/watch/gulp.js
- Adding chalk for clearer messaging and a stronger identity.
- Existing messages have been updated to use chalk.
This commit paves the way for more specific errors / guidance when trying to run the server or build tasks, in order to give the user clear feedback on how to fix their issue.
> Better branding and messaging.

- .gitignore
- karma.conf.js
Updating to make use of the test suites new code coverage capabilities.
> Test Suite: Code Coverage

- karma.conf.js
The front-end test suite package was updated to be compatible with Karma 0.13.x. This PR gets the karma settings file `karma.conf.js` in line with the changes. I'll be auto-accepting my PR since I'm the only member of staff that uses or knows the test suite inside out.
(This'll make Paddy chuckle!)
> Removing JUnit settings and adding coverage options.

- run/tasks/build/index.js
- run/tasks/images/_common.js
- run/tasks/images/index.js
Image minifcation no longer goes into an obscure 'img-min' directory. Instead, optimized images go straight into the 'dist/img' folder.
> Image Minification: Output Destination.

- package.json
- run/tasks/build/index.js
- Removing the merge stream integration which hasn't been needed for a while.
> Build Task: Simplifying Streams.

- run/tasks/html/index.js
Sorting out nested HTML files being copied to dist folder.
> Task: Nested HTML.

- README.md
- karma.conf.js
- package.json
- Updating Karma configuration to work with Webpack.
- Bumping project version to 2.0 (considering depth of recent changes).
> Test Suite: Upgrading for Webpack.

- package.json
- run/config.js
- Updating webserver defaults so they're compatible with deployments to environments such as Heroku. All previous functionality still preserved.
- Updating npm scripts and removing two old scripts that are not used or needed by the pre-commit hook.
> Webserver defaults.

- .dockerignore
- .gitignore
- Makefile
fixes #80 - removing docker entirely as this should be handled by the larger project that embeds the skeleton
> removing docker and cleaning up makefile

- Makefile
- package.json
Since people are good at suggesting and not so much at PR'ing - here ya go
> switching gulp use to npm run for cleanliness

- .npmrc
Saves the exact version of a node module https://docs.npmjs.com/misc/config#save-exact
> Added .npmrc file with save-exact=true

- .eslintrc
The tool I used to create this added a load of extra definitions that we don't need/want
> Fixed eslint definitions

- .jshintrc
- run/config.js
- run/index.js
- run/tasks/build/index.js
- run/tasks/default/index.js
- run/tasks/html/index.js
- run/tasks/images/index.js
- run/tasks/jscs/index.js
- run/tasks/lint/index.js
- run/tasks/scripts/index.js
- run/tasks/server/index.js
- run/tasks/styles/index.js
- run/tasks/test/index.js
- run/tasks/watch/index.js
The front-end skeleton files should be no exception to our linting and validation rules. This PR sees all files conform to the rules, and the JSHint / JSCS tasks updated to watch the test suite as if they were source files.
> Linting Files.

- package.json
Add a post hook to ensure CSS/JS files are built and minified.
> Adding post hook for css/js minified build

- README.md
> README Update: Referencing quick start guide.

- .gitignore
- package.json
- Updating NPM scripts to run linting before the test suite.
- Also updating filename of test suite output.
> Test Suite: NPM Scripts and File Ignoring.

- run/config.js
> Removing an obsolete setting from the watch task.

- run/config.js
> Ensuring BrowserSync watches HTML.

- .editorconfig
Ensuring the EditorConfig matches whats on the EditorConfig rehabstudio repository.
> EditorConfig Updates.

- run/config.js
- web-manifest.json
- Adding a basic web manifest which should prompt developers to use it more frequently.
> Web Manifest

- README.md
- karma.conf.js
- run/tasks/test/wrapper.js
> Moving test suite bundles from 'a bundle per spec' to 'one bundle overall'.
> Test Suite: Bundle Files

- run/config.js
- run/tasks/styles/index.js
Moving sourcemap settings into styles options as they're now CSS specific.
> CSS: Sourcemap Settings

- karma.conf.js
- run/config.js
- run/tasks/clean/index.js
* Moving the test results path to a DRYer location.
* Re-using it accordingly.
NOTE: It looks like there's been a lot of changes to the configuration but there hasn't. It's just been re-nesting.
> Configuration Update

- package.json
- run/config.js
- run/tasks/images/index.js
* Updating `imagemin` to the latest version.
* Re-organising the image task options to cater to new `imagemin` instructions.
> Imagemin: Latest Updates.
