rehabstudio/fe-skeleton

run/tasks/styles/gulp.js
Updating prefixer common path, removing .browsers as this makes the path too specific and ignoring any other prefixer settings within the settings object.
=> Updating prefixer object literal path removing browsers key  

README.md, package.json, run/tasks/styles/_common.js, run/tasks/styles/gulp.js
The performance gains listed in #11 are reason enough to change, and also given the fact that `node-sass` is more stable than ever. A nice added bonus is that we'll lose our Ruby dependency.
This PR effectively fixes #11.
=> Use node-sass over ruby-sass.

package.json, run/tasks/scripts/gulp.js, run/tasks/styles/gulp.js
Now that we have removed RequireJS from the build, there is no need to have nested requires within the browserify sub-functions. For some reason, moving these requires up to the top level results in much faster compilation speeds upon recurring tasks / watch-triggered runs.
My only guess is that node is somehow caching the files that it's previously loaded and somehow retaining this cache throughout recurring executions. Speed differences are listed below:
Nested Requires:
```
[10:33:33] Finished 'scripts' after 1.48 s
[10:33:36] Finished 'scripts' after 1.52 s
[10:33:38] Finished 'scripts' after 1.6 s
[10:33:41] Finished 'scripts' after 1.51 s
[10:33:43] Finished 'scripts' after 1.52 s
```
Average after 5 runs is 1526ms
Top-level Requires:
```
[10:34:42] Finished 'scripts' after 859 ms …
```
=> Removing nested requires in scripts task

package.json, run/_global.js, run/tasks/scripts/_common.js, run/tasks/scripts/gulp.js
The accepted convention in gulp plugins on how to handle sourcemaps is via a popular plugin called `gulp-sourcemaps`. We couldn't use these until recently, as the currently uglification plugin `gulp-uglifyjs` doesn't work well with `gulp-sourcemaps`.
This uglification plugin has just became blacklisted for not doing things "the gulp way". I've found an alternative that happens to also play very well with `gulp-sourcemaps`.
This PR swaps our sourcemaps implementation to use the now commonly accepted `gulp-sourcemaps` plugin, as well as updates our uglifying to `gulp-uglify`. Another added result of this refactoring is that we have one fewer node packages than before and plays into an upcoming PR where we will bring sourcemaps to stylesheets using the same `gulp-sourcemap` plugin.
There are …
=> Update sourcemap and uglify implementations

run/tasks/lint/gulp.js
Currently the linter isn't erroring whenever warnings or errors are found in JS source code. This means the process exits with a `0` (success) and if the linter is in a gulp pipeline it won't stop the execution of anything after it.
This PR sees that the linter method correctly errors when a warning or error in a JS source file is found, and exits the process with the correct code.
=> Linter should fail on JS errors.

package.json
This should encourage people to keep their build tool depenencies (`"devDependencies"`) and their project dependencies separate.
=> Adding blank dependencies to package.json

README.md, package.json, run/tasks/server/_common.js, run/tasks/server/gulp.js
Adding a webserver allows us to host our `dist` folder on a specific port which'll help when prototyping or examples.
=> Adding a webserver task

run/tasks/test/gulp.js
Ensuring that gulp is given the exit code from karma, so that the gulp task exits with the same code.
Example for a failing test suite:
```
gulp test;
echo $?;
```
=> Karma + Gulp: Exit Codes

run/tasks/styles/_common.js
Errors during watch currently break. This will stop watch from stopping.
=> Updating gulp-sass settings.

run/index.js, run/tasks/build/gulp.js, run/tasks/server/gulp.js
Updating the code base with some extra warnings on a few our of methods.
1) `build` will now warn if it's being called without any script or style bundles being defined.
2) `server` will error and exit if it's being called without a `dist` folder existing to host.
Fixes #43.
=> Updated task warnings and errors

.jscsrc
Pushing something we've done on Miyagi to the JSCS rules which ensures that if there's function documentation, that it's actually useful, formatted correctly, and describes parameters / returns correctly.
=> JSDoc formatting is now validated.

run/index.js, run/tasks/build/index.js, run/tasks/html/_common.js, run/tasks/html/index.js, run/tasks/watch/_common.js, run/tasks/watch/index.js
One of the biggest bugbears with the current code base is that HTML assets can only be moved into the `destPath` whenever running `gulp build`. This change modularises the HTML assets so they can be watched via `gulp watch`. Fixes #41.
=> Modularizing HTML feature so it can be watched.

package.json, run/tasks/jscs/index.js, run/tasks/lint/index.js
Lint / JSCS output was virtually nothing if there were no errors, making users wonder if it ran at all. This will show the files being scanned to prove it has worked.
=> Lint / JSCS: Output file names.

karma.conf.js, run/tasks/test/_shims.js
Adding a shims file for shimming missing PhantomJS functionality such as `Function.prototype.bind`.
=> Test Suite: Shims.

run/tasks/styles/_common.js
Fixing sourcemaps by using a different output style. It's a strange bug with no real sign of surfacing on any of the issue trackers for `gulp-sass`, `gulp-autoprefixer` or `libsass` but the fix is trivial enough and doesn't impact our output file sizes too much.
=> Fixing CSS Sourcemaps.

run/_global.js, run/tasks/jscs/_common.js, run/tasks/jscs/index.js, run/tasks/lint/_common.js, run/tasks/lint/index.js
- Cleaning up the global settings file to adhere to JSCS/Linting conventions.
- Updating JSCS and Lint tasks to use the same path configuration variable.
=> Linting: DRY variables.

package.json, run/index.js
Removing ES6 promise polyfill now that chromium version of node under the hood is recent enough to support them natively.
=> Removing ES6 Promise Polyfill.

.jshintrc
A simple one that is just updating our code linter to tell it that ES6/ES2015 syntax in our builds shouldn't be flagged as erroneous.
=> Improvement: ES6/ES2015 Syntax.

run/tasks/build/index.js
Fixing the build task warning for no scripts being defined so it works with new webpack configuration structure.
=> Build Task: Bundle warning with Webpack.

.editorconfig, package.json
- Updating EditorConfig so that it will have proper formatting for Travis CI and Node package files.
- Updating `package.json` so follows standard package formatting. This will ensure that adding new packages won't result in a rewrite of the entire file.
=> EditorConfig / Package.json Updates

README.md, package.json, run/tasks/jscs/index.js, run/tasks/jshint/index.js
The commit hook is becoming no longer necessary; the development team is more aware of the standards we need to keep. There's been multiple discussions around the topic amongst the team at various levels and that's given the topic more prominence. We now have our jenkins cluster set up and ready for project integrations.
The miyagi team have standards, linting, formatting and unit testing as part of their everyday workflow and once these team members disperse onto new projects, hopefully they'll take their regimented workflow with them. We have to entrust the lead developers on the project to keep code conforming to the rules and ensure that unit tests are being written.
=> Pre-Commit Hook Removal

app.yaml
To solve #52 in place of a docker/rehab-labs solution
=> adding app.yaml for default static hosting of content on appengine

.eslintrc.json
`foo('apple', 'banana', ['orange', 'grape', 'melon'])`  
and not 
`foo('apple','banana',['orange','grape','melon'])`
=> Add eslint rule: spaces should follow commas

.gitignore, karma.conf.js, package.json, run/config.js
Uses `babel-istanbul` and `karma-coverage` to add code coverage information in the form of Cobertura XML that can be used by Jenkins.
=> Test Suite: Code Coverage

package.json, run/config.js, run/index.js, run/tasks/build/index.js, run/tasks/clean/index.js, run/tasks/copy/index.js
Build Task:
* Now uses `run-sequence` npm module to ensure that `clean` task is run first, before all the other build tasks run in parallel (`styles`, `html`, `scripts`, `images`, `copy`).
Copy Task (NEW):
* Contains the copy logic that used to be in the build task. The build task is now essentially logicless with all build processes having their own gulp task.
Clean Task (NEW):
* Removes `./test-results/` and `./dist/` before performing a build. This ensures old assets (such as old images, or files who have had their source file renamed) will be removed correctly.
=> Adding copy and clean tasks.

run/index.js, run/tasks/build/index.js, run/tasks/default/index.js, run/tasks/watch/index.js
Currently the `index.js` for the task runner has it's own override map to ensure that if you load `build` or other high-level tasks, that it also a bunch of other tasks beforehand. This is probably better kept with each of the tasks themselves and treated like dependencies. I don't see any use in separating these dependencies and storing them somewhere other than the tasks themselves.
=> Task Loading

.eslintrc.json
Indentation rules are currently forcing switch statements to look like this:
```
switch(testVar) {
case 'hello':
console.log('world');
break;
}
```
Which is an oversight; it should allow for normal indentation like this:
```
switch(testVar) {
case 'hello':
console.log('world');
break;
}
```
=> Fixing switch statement indentation.
